root = "."
tmp_dir = "tmp"

[build]
# The directory where the main package is located
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
include_ext = ["go", "html"]
exclude_dir = ["tmp", "vendor"]
delay = 1000 # ms
stop_on_error = true
kill_delay = "0s"
send_interrupt = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true 