name: Build Trellis

on:
  push:
    paths:
      - 'scripts/trellis/**'
  pull_request:
    paths:
      - 'scripts/trellis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Change to trellis directory
      run: cd scripts/trellis

    - name: Download Go modules
      run: |
        cd scripts/trellis
        go mod download

    - name: Verify Go modules
      run: |
        cd scripts/trellis
        go mod verify

    - name: Run Go vet
      run: |
        cd scripts/trellis
        go vet ./...

    - name: Build executables
      run: |
        cd scripts/trellis
        chmod +x build.sh
        ./build.sh

    - name: Verify executable exists
      run: |
        cd scripts/trellis
        ls -la bin/
        test -f bin/update_recordings